title: Juncture Site
tagline: Visual Essays
banner: "/images/header.jpg"
bannerHeight: 400
favicon: "/images/favicon.svg"

# When using a custom domain these fields must be updated to match
# the account and repository name in the forked repository
acct: JSTOR-Labs
repo: juncture-site

######################################################
# Defines options shown in the header  navigation menu
######################################################
nav:
- label: About
  icon: info
  path: "/about"
- label: Help
  icon: question
  path: "/help"
#- label: Contact Us
#  icon: envelope
#  path: "/contact-us"

# If the /contact-us path is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form
# A valid toEmail address is required. Other fields are optional
#contactForm:
#  toEmail:
#  - name@example.org
#  subject: Juncture feedback
#  fromRoles:
#  - Undergraduate Student
#  - Graduate Student
#  - College/University Faculty
#  - Independent Scholar
#  - Other
